nixosTests.bittorrent: avoid use of an alias
By default the use of alias generates warning:

    $ nix build --no-link -f. nixosTests.bittorrent
    evaluation warning: transmission has been renamed to transmission_3 since transmission_4 is also available. Note that upgrade caused data loss for some users so backup is recommended (see NixOS 24.11 release notes for details)

When alaises are disabled that causes the eval failure:

       error: attribute 'transmission' missing
       at /home/slyfox/dev/git/nixpkgs/nixos/tests/bittorrent.nix:24:36:
           23|   transmissionConfig = { ... }: {
           24|     environment.systemPackages = [ pkgs.transmission ];
             |                                    ^
           25|     services.transmission = {
       Did you mean one of transmission_3 or transmission_4?