laurel: fix compiling on aarch64-linux
This solves the following build error:

~~~
error: linker `aarch64-linux-gnu-gcc` not found
  |
  = note: No such file or directory (os error 2)
~~~

Which happens on aarch64-linux and armv7-linux because upstream
redirects the linker for that platform in
https://github.com/threathunters-io/laurel/blob/v0.6.3/.cargo/config.toml

Since there is nothing else besides linker redirects in there, we simply
delete the whole file.